<a href="https://colab.research.google.com/github/naimahsesay08-dot/Emmy-Award-Project-/blob/main/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas
import pandas as pd
import matplotlib.pyplot as plt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [19]:
!git clone https://github.com/frontiertechinstitute/datasets.git
data = pd.read_csv('datasets/Emmy Awards and Nominees Data/emmy_cleaned.csv')
data.head(5)

fatal: destination path 'datasets' already exists and is not an empty directory.

,category,production,type,title,distributor,producer,year
0,Outstanding Character Voice-Over Performance -...,NaN,Nominee,black-ish: Election Special (Part 2),ABC,ABC,2021
1,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Bridgerton,Netflix,A Netflix Original Series in association with ...,2021
2,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Family Guy,FOX,20th Television Animation,2021
3,Outstanding Character Voice-Over Performance -...,NaN,Nominee,Archer,FX Networks,FX Productions,2021
4,Outstanding Production Design For A Narrative ...,"Elisabeth Williams, Production Designer",Nominee,The Handmaid's Tale,Hulu,"Hulu, MGM, Daniel Wilson Productions, The Litt...",2021

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29678 entries, 0 to 29677
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category     29678 non-null  object
 1   production   26825 non-null  object
 2   type         29678 non-null  object
 3   title        29678 non-null  object
 4   distributor  29675 non-null  object
 5   producer     29678 non-null  object
 6   year         29678 non-null  int64
dtypes: int64(1), object(6)
memory usage: 1.6+ MB

In [21]:
data.shape

(29678, 7)

In [25]:
data.duplicated().sum()

np.int64(321)

In [26]:
data.isnull().sum()

category          0
production     2853
type              0
title             0
distributor       3
producer          0
year              0
dtype: int64

In [30]:
data['category'].unique()[:20]

array(['Outstanding Character Voice-Over Performance - 2021',
       'Outstanding Production Design For A Narrative Contemporary Program (One Hour Or More) - 2021',
       'Outstanding Production Design For A Narrative Period Or Fantasy Program (One Hour Or More) - 2021',
       'Outstanding Production Design For A Narrative Program (Half-Hour) - 2021',
       'Outstanding Production Design For A Variety, Reality Or Competition Series - 2021',
       'Outstanding Production Design For A Variety Special - 2021',
       'Outstanding Casting For A Comedy Series - 2021',
       'Outstanding Casting For A Drama Series - 2021',
       'Outstanding Casting For A Limited Or Anthology Series Or Movie - 2021',
       'Outstanding Cinematography For A Multi-Camera Series - 2021',
       'Outstanding Cinematography For A Single-Camera Series (One Hour) - 2021',
       'Outstanding Cinematography For A Limited Or Anthology Series Or Movie - 2021',
       'Outstanding Cinematography For A Nonfiction Program - 2021',
       'Outstanding Period Costumes - 2021',
       'Outstanding Contemporary Costumes - 2021',
       'Outstanding Directing For A Comedy Series - 2021',
       'Outstanding Directing For A Drama Series - 2021',
       'Outstanding Directing For A Limited Or Anthology Series Or Movie - 2021',
       'Outstanding Directing For A Variety Series - 2021',
       'Outstanding Directing For A Variety Special - 2021'], dtype=object)

In [31]:
data["type"].unique()

array(['Nominee', 'Winner'], dtype=object)

In [32]:
data["production"] = data["production"].fillna("Unknown")
data["distributor"] = data["distributor"].fillna("Unknown")

In [33]:
data.duplicated().sum()

np.int64(321)

In [35]:
data=data.drop_duplicates()

In [36]:
data.duplicated().sum()

np.int64(0)

In [37]:
data.shape

(29357, 7)

In [39]:
data["category"].value_counts().head(10)

category
Outstanding Technical Direction, Camerawork, Video For A Miniseries, Movie Or A Special - 2007            117
Outstanding Technical Direction, Camerawork, Video For A Miniseries, Movie Or A Special - 2008            111
Outstanding Drama Series - 2021                                                                           109
Outstanding Animated Program - 2019                                                                       102
Outstanding Technical Direction, Camerawork, Video Control For A Miniseries, Movie Or A Special - 2013    101
Outstanding Writing For A Variety Series - 2019                                                           101
Outstanding Technical Direction, Camerawork, Video Control For A Miniseries, Movie Or A Special - 2009    100
Outstanding Technical Direction, Camerawork, Video Control For A Miniseries, Movie Or A Special - 2011    100
Outstanding Comedy Series - 2021                                                                           99
Outstanding Technical Direction, Camerawork, Video Control For A Miniseries, Movie Or A Special - 2010     98
Name: count, dtype: int64

In [40]:
data.to_csv("emmy_awards_cleaned_final.csv", index=False)